import type { Store } from "./schemas";

// Single seeded project per the cut-scope MVP (docs/context/mvp-revisado-110min.md):
// no project-creation flow, no multi-project. Matches the demo example in
// docs/plan/PLAN-MAESTRO.md §2 (a distributed team validating a signup flow).
//
// Tasks are seeded with githubIssueNumber: null — P3's GitHub sync links them
// to real issues in the target repo. Never invent issue numbers that don't exist.

const NOW = "2026-09-12T18:00:00.000Z";

export const seedStore: Store = {
  project: {
    id: "proj-signup-validation",
    name: "Validación de flujo de registro",
    charter: {
      purpose: "Validar el flujo de registro con usuarios reales antes de escalarlo.",
      sponsorName: "Equipo NERV",
      leadMemberId: "member-lead",
      beneficiaries: "Usuarios nuevos del producto; equipo de crecimiento.",
      scopeIn: ["Flujo de registro con 5 usuarios de prueba", "Instrumentación básica de conversión"],
      scopeOut: ["Onboarding completo", "Integraciones de pago"],
      deliverables: ["Reporte de validación con 5/5 usuarios completando el registro"],
      constraints: ["Ventana de construcción de 110 minutos"],
      assumptions: ["El equipo tiene acceso al repositorio de GitHub del proyecto"],
      successCriteria: ["5 de 5 usuarios de prueba completan el registro sin asistencia"],
      status: "draft",
      approvedBy: null,
      approvedAt: null,
    },
    objective: {
      id: "obj-1",
      statement: "5 de 5 usuarios de prueba completan el registro sin asistencia.",
      ownerMemberId: "member-lead",
      targetAt: "2026-09-19T00:00:00.000Z",
    },
    milestones: [
      {
        id: "ms-1",
        objectiveId: "obj-1",
        title: "Instrumentar y lanzar el flujo",
        dueAt: "2026-09-14T00:00:00.000Z",
        acceptanceCriteria: "Flujo desplegado con eventos de analítica en cada paso.",
        raci: {
          accountableId: "member-lead",
          responsibleIds: ["member-lead"],
          consultedIds: ["member-2"],
          informedIds: ["member-3"],
        },
      },
      {
        id: "ms-2",
        objectiveId: "obj-1",
        title: "Ejecutar prueba con 5 usuarios",
        dueAt: "2026-09-19T00:00:00.000Z",
        acceptanceCriteria: "5 sesiones de usuario registradas con resultado.",
        raci: {
          accountableId: "member-lead",
          responsibleIds: ["member-2", "member-3"],
          consultedIds: ["member-lead"],
          informedIds: [],
        },
      },
    ],
    version: 1,
    updatedAt: NOW,
  },
  members: [
    {
      id: "member-lead",
      projectId: "proj-signup-validation",
      authSubject: "fake:lead",
      displayName: "Lead del proyecto",
      accessRole: "lead",
      locale: "es",
      timeZone: "America/Bogota",
    },
    {
      id: "member-2",
      projectId: "proj-signup-validation",
      authSubject: "fake:member-2",
      displayName: "Miembro 2",
      accessRole: "member",
      locale: "es",
      timeZone: "America/Bogota",
    },
    {
      id: "member-3",
      projectId: "proj-signup-validation",
      authSubject: "fake:member-3",
      displayName: "Miembro 3",
      accessRole: "member",
      locale: "es",
      timeZone: "America/Bogota",
    },
  ],
  tasks: [
    {
      id: "task-1",
      projectId: "proj-signup-validation",
      origin: "manual",
      milestoneId: "ms-1",
      title: "Instrumentar eventos de analítica en el formulario",
      description: "",
      workflowState: "done",
      responsibleId: "member-lead",
      dueAt: "2026-09-13T00:00:00.000Z",
      estimateMinutes: 120,
      acceptanceCriteria: "Eventos visibles en el panel de analítica.",
      blocked: false,
      githubIssueNumber: null,
      githubUrl: null,
      version: 1,
    },
    {
      id: "task-2",
      projectId: "proj-signup-validation",
      origin: "manual",
      milestoneId: "ms-1",
      title: "Desplegar el flujo a un entorno de prueba",
      description: "",
      workflowState: "doing",
      responsibleId: "member-lead",
      dueAt: "2026-09-14T00:00:00.000Z",
      estimateMinutes: 90,
      acceptanceCriteria: "URL de prueba accesible para el equipo.",
      blocked: false,
      githubIssueNumber: null,
      githubUrl: null,
      version: 1,
    },
    {
      id: "task-3",
      projectId: "proj-signup-validation",
      origin: "manual",
      milestoneId: "ms-1",
      title: "Revisar copys y mensajes de error del formulario",
      description: "",
      workflowState: "todo",
      responsibleId: "member-2",
      dueAt: null,
      estimateMinutes: 45,
      acceptanceCriteria: "Copys revisados por el lead.",
      blocked: false,
      githubIssueNumber: null,
      githubUrl: null,
      version: 1,
    },
    {
      id: "task-4",
      projectId: "proj-signup-validation",
      origin: "manual",
      milestoneId: "ms-2",
      title: "Reclutar 5 usuarios de prueba",
      description: "",
      workflowState: "doing",
      responsibleId: "member-2",
      dueAt: "2026-09-16T00:00:00.000Z",
      estimateMinutes: 60,
      acceptanceCriteria: "5 usuarios confirmados con horario asignado.",
      blocked: true,
      githubIssueNumber: null,
      githubUrl: null,
      version: 1,
    },
    {
      id: "task-5",
      projectId: "proj-signup-validation",
      origin: "manual",
      milestoneId: "ms-2",
      title: "Ejecutar sesiones de prueba y registrar resultados",
      description: "",
      workflowState: "todo",
      responsibleId: "member-3",
      dueAt: "2026-09-19T00:00:00.000Z",
      estimateMinutes: 180,
      acceptanceCriteria: "5 resultados registrados con evidencia.",
      blocked: false,
      githubIssueNumber: null,
      githubUrl: null,
      version: 1,
    },
    {
      id: "task-6",
      projectId: "proj-signup-validation",
      origin: "manual",
      milestoneId: "ms-2",
      title: "Redactar reporte de validación",
      description: "",
      workflowState: "todo",
      responsibleId: "member-lead",
      dueAt: "2026-09-19T00:00:00.000Z",
      estimateMinutes: 60,
      acceptanceCriteria: "Reporte compartido con el equipo.",
      blocked: false,
      githubIssueNumber: null,
      githubUrl: null,
      version: 1,
    },
  ],
  messages: [
    {
      id: "msg-1",
      projectId: "proj-signup-validation",
      authorMemberId: "member-lead",
      text: "Arrancamos: objetivo es 5/5 usuarios completando el registro sin asistencia.",
      createdAt: NOW,
    },
  ],
};
